from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QCheckBox,
    QHBoxLayout,
    QLabel,
    QProgressBar,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from config import (
    approved_model_file_path,
    format_size,
    get_default_model,
    save_model_path,
)
from ui.components import header_label, profile_scroll_area
from ui.documents.view import DocumentsHubWidget
from ui.onboarding.workers import DefaultModelDownloadWorker
from ui.profile.form import ProfileForm


def _hero_label(text: str) -> QLabel:
    lbl = QLabel(text)
    lbl.setStyleSheet("font-size: 56pt; font-weight: bold;")
    lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
    return lbl


_NAV_BTN_SIZE = (100, 38)


def _onboarding_nav_row(*, on_back, on_continue, continue_enabled: bool = True) -> QHBoxLayout:
    row = QHBoxLayout()
    row.setSpacing(12)
    row.addStretch()

    if on_back is None:
        spacer = QWidget()
        spacer.setFixedSize(*_NAV_BTN_SIZE)
        row.addWidget(spacer)
    else:
        back_btn = QPushButton("Back")
        back_btn.setObjectName("attachButton")
        back_btn.setFixedSize(*_NAV_BTN_SIZE)
        back_btn.clicked.connect(on_back)
        row.addWidget(back_btn)

    cont_btn = QPushButton("Continue")
    cont_btn.setFixedSize(*_NAV_BTN_SIZE)
    cont_btn.setEnabled(continue_enabled)
    cont_btn.clicked.connect(on_continue)
    row.addWidget(cont_btn)

    row.continue_btn = cont_btn  # type: ignore[attr-defined]
    return row


class WelcomeScreen(QWidget):
    start_clicked = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(40, 40, 40, 40)
        layout.setSpacing(32)

        layout.addStretch()
        layout.addWidget(_hero_label("Welcome!"))

        policy = QTextEdit()
        policy.setReadOnly(True)
        policy.setFixedHeight(180)
        policy.setFixedWidth(520)
        policy.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        policy.setPlainText(
            "PRIVACY AND USAGE POLICY\n\n"
            "This application is designed to process medical documents locally on your device. "
            "Your profile, uploaded documents, parsed text, chat history, vector database, and "
            "generated reports are stored locally.\n\n"
            "The application is not a medical device and does not replace professional medical "
            "advice, diagnosis, or treatment. Answers generated by the AI model may be incomplete "
            "or incorrect and should be verified with a qualified healthcare professional.\n\n"
            "By continuing, you confirm that you understand these limitations and agree to use "
            "the application under your own responsibility."
        )
        policy_row = QHBoxLayout()
        policy_row.addStretch()
        policy_row.addWidget(policy)
        policy_row.addStretch()
        layout.addLayout(policy_row)

        self._accept_checkbox = QCheckBox("I have read and accept the policy")
        checkbox_row = QHBoxLayout()
        checkbox_row.addStretch()
        checkbox_row.addWidget(self._accept_checkbox)
        checkbox_row.addStretch()
        layout.addLayout(checkbox_row)

        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self._start_btn = QPushButton("Start")
        self._start_btn.setFixedSize(*_NAV_BTN_SIZE)
        self._start_btn.setEnabled(False)
        self._start_btn.clicked.connect(self.start_clicked.emit)
        self._accept_checkbox.toggled.connect(self._start_btn.setEnabled)
        btn_row.addWidget(self._start_btn)
        btn_row.addStretch()
        layout.addLayout(btn_row)

        layout.addStretch()


class ProfileSetupScreen(QWidget):
    continue_clicked = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        outer = QVBoxLayout(self)
        outer.setContentsMargins(40, 40, 40, 40)
        outer.setSpacing(12)

        outer.addWidget(header_label("To get started, please fill in your profile data:"))

        form_container = QWidget()
        form_wrap = QHBoxLayout(form_container)
        form_wrap.setContentsMargins(0, 0, 0, 0)
        form_wrap.addStretch()
        self._form = ProfileForm(self)
        self._form.setMinimumWidth(440)
        self._form.setMaximumWidth(560)
        self._form.submitted.connect(self._on_continue)
        form_wrap.addWidget(self._form)
        form_wrap.addStretch()

        outer.addWidget(profile_scroll_area(form_container), stretch=1)

        outer.addLayout(_onboarding_nav_row(on_back=None, on_continue=self._on_continue))

    def _on_continue(self):
        self._form.save()
        self.continue_clicked.emit()

    def reload(self):
        self._form.reload()


class ModelDownloadScreen(QWidget):
    proceed_clicked = Signal(str)
    back_clicked = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._worker: DefaultModelDownloadWorker | None = None
        self._model_path: str | None = None

        layout = QVBoxLayout(self)
        layout.setContentsMargins(40, 40, 40, 40)
        layout.setSpacing(16)

        layout.addStretch()

        layout.addWidget(header_label("Loading the default AI model to your device..."))

        self._info_label = QLabel("")
        self._info_label.setObjectName("statusLabel")
        self._info_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self._info_label)

        self._current_file_label = QLabel("Preparing download...")
        self._current_file_label.setObjectName("statusLabel")
        self._current_file_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self._current_file_label)

        bar_row = QHBoxLayout()
        bar_row.addStretch()
        self._progress = QProgressBar()
        self._progress.setMinimum(0)
        self._progress.setMaximum(1000)
        self._progress.setValue(0)
        self._progress.setTextVisible(False)
        self._progress.setFixedWidth(640)
        bar_row.addWidget(self._progress)
        bar_row.addStretch()
        layout.addLayout(bar_row)

        self._size_label = QLabel("0 B / —")
        self._size_label.setObjectName("statusLabel")
        self._size_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self._size_label)

        layout.addStretch()
        nav_row = _onboarding_nav_row(
            on_back=self.back_clicked.emit,
            on_continue=self._on_continue,
            continue_enabled=False,
        )
        self._continue_btn = nav_row.continue_btn
        layout.addLayout(nav_row)

    def start(self):
        if self._worker and self._worker.isRunning():
            return
        model = get_default_model()
        self._info_label.setText(model["display_name"])
        model_path = approved_model_file_path(model)
        mmproj_path = approved_model_file_path(model, model["mmproj_local"])
        if model_path.exists() and mmproj_path.exists():
            total = model_path.stat().st_size + mmproj_path.stat().st_size
            self._progress.setValue(1000)
            self._size_label.setText(f"{format_size(total)} / {format_size(total)}")
            self._on_done(str(model_path))
            return

        self._continue_btn.setEnabled(False)
        self._current_file_label.setText("Starting...")
        self._size_label.setText("0 B / —")
        self._worker = DefaultModelDownloadWorker()
        self._worker.progress.connect(self._on_progress)
        self._worker.finished.connect(self._on_done)
        self._worker.error_occurred.connect(self._on_error)
        self._worker.start()

    def _on_progress(self, downloaded: int, total: int, name: str):
        self._current_file_label.setText(f"Downloading {name}")
        if total > 0:
            self._progress.setValue(int(downloaded * 1000 / total))
            self._size_label.setText(f"{format_size(downloaded)} / {format_size(total)}")
        else:
            self._progress.setValue(0)
            self._size_label.setText(format_size(downloaded))

    def _on_done(self, model_path: str):
        self._model_path = model_path
        self._progress.setValue(1000)
        self._current_file_label.setText("Download complete")
        save_model_path(model_path)
        self._continue_btn.setEnabled(True)

    def _on_error(self, error: str):
        self._current_file_label.setText(f"Error: {error}")
        self._continue_btn.setEnabled(False)

    def _on_continue(self):
        if not self._model_path:
            return
        self.proceed_clicked.emit(self._model_path)


class DocumentsSetupScreen(QWidget):
    proceed_clicked = Signal()
    back_clicked = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(40, 40, 40, 40)
        layout.setSpacing(16)

        layout.addWidget(
            header_label("Upload your medical documents now, or skip and add them later")
        )

        self.docs = DocumentsHubWidget(self)
        layout.addWidget(self.docs, stretch=1)

        nav_row = _onboarding_nav_row(
            on_back=self.back_clicked.emit,
            on_continue=self._on_continue,
        )
        self._continue_btn = nav_row.continue_btn
        layout.addLayout(nav_row)

    def _on_continue(self):
        if self.docs.is_busy():
            return
        self.proceed_clicked.emit()
